"""Explicit live create-only report test; tokens never printed or persisted."""
import argparse
import copy
import json
import re
import urllib.error
import urllib.request
from pathlib import Path

p = argparse.ArgumentParser()
p.add_argument('--allow-live-write', action='store_true', required=True)
p.add_argument('--output', type=Path, required=True)
a = p.parse_args()
repo = Path(__file__).resolve().parents[2]
client = (repo / 'android-app/src/com/example/winavf/CompatibilityUpload.java').read_text()
key = re.search(r'String KEY="([^"]+)"', client).group(1)
project = re.search(r'String PROJECT="([^"]+)"', client).group(1)
checks = []

def request(url, data=None, token=None, method=None):
    headers = {'Content-Type': 'application/json'}
    if token:
        headers['Authorization'] = 'Bearer ' + token
    body = None if data is None else json.dumps(data).encode()
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=25) as response:
            return response.status, json.loads(response.read(65536))
    except urllib.error.HTTPError as error:
        # Do not print the response or request authentication material.
        error.read(65536)
        return error.code, {}

def expect(name, result, expected):
    status, data = result
    checks.append({'check': name, 'status': status, 'expected': expected, 'pass': status == expected})
    if status != expected:
        save('FAIL')
        raise SystemExit(name + '=FAIL HTTP ' + str(status))
    print(name + '=PASS HTTP ' + str(status), flush=True)
    return data

def save(status):
    a.output.parent.mkdir(parents=True, exist_ok=True)
    a.output.write_text(json.dumps({'status': status, 'project': project,
        'checks': checks, 'live_test_report_created': any(c['check'] == 'VALID_CREATE' and c['pass'] for c in checks),
        'limits': ['One synthetic release-validation report retained in developer database',
                   'No claim of global anti-abuse, TTL, admin policy or database edition verification']}, indent=2) + '\n')

identity_url = 'https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=' + key
identities = []
try:
    for name in ('AUTH_A', 'AUTH_B'):
        identities.append(expect(name, request(identity_url, {'returnSecureToken': True}), 200))
    first, second = identities
    uid, token = first['localId'], first['idToken']
    base = 'https://firestore.googleapis.com/v1/projects/' + project + '/databases/(default)/documents'
    document = 'projects/' + project + '/databases/(default)/documents/compatibility_reports/' + uid + '/runs/'
    string = lambda value: {'stringValue': value}
    fields = {'schemaVersion': {'integerValue': '1'}, 'consent': {'booleanValue': True},
        'appVersion': string('1.0/14-release-validation'), 'androidApi': {'integerValue': '36'},
        'androidRelease': string('16'), 'manufacturer': string('U-AVF validation'),
        'model': string('Synthetic release API test'),
        'results': {'mapValue': {'fields': {key: string('not_tested') for key in
            ('arm64','avf','permissions','storage','iso','platform')}}},
        'runtime': {'mapValue': {'fields': {key: string('not_tested') for key in ('boot','vsock','openGL')}}}}
    def create(run='0', values=None, owner_token=token, create_only=True):
        write = {'update': {'name': document + run, 'fields': values or fields},
            'updateTransforms': [{'fieldPath':'submittedAt','setToServerValue':'REQUEST_TIME'}]}
        if create_only:
            write['currentDocument'] = {'exists': False}
        return request(base + ':commit', {'writes': [write]}, owner_token)
    expect('VALID_CREATE', create(), 200)
    expect('NO_AUTH_CREATE_DENIED', create('1', owner_token=None), 403)
    expect('OWN_READ_DENIED', request(base + '/compatibility_reports/' + uid + '/runs/0', token=token), 403)
    expect('OTHER_READ_DENIED', request(base + '/compatibility_reports/' + uid + '/runs/0', token=second['idToken']), 403)
    expect('UPDATE_DENIED', create(create_only=False), 403)
    expect('DELETE_DENIED', request(base + ':commit', {'writes':[{'delete':document+'0'}]}, token), 403)
    expect('OTHER_OWNER_CREATE_DENIED', create('1', owner_token=second['idToken']), 403)
    bad = copy.deepcopy(fields); bad['consent'] = {'booleanValue': False}
    expect('NO_CONSENT_DENIED', create('1', bad), 403)
    bad = copy.deepcopy(fields); bad['role'] = string('admin')
    expect('EXTRA_FIELD_DENIED', create('1', bad), 403)
    bad = copy.deepcopy(fields); bad['manufacturer'] = string('x' * 100)
    expect('OVERSIZE_DENIED', create('1', bad), 403)
    expect('RUN_LIMIT_DENIED', create('32'), 403)
    save('PASS')
finally:
    # Only identities generated by this test; no existing users/reports touched.
    for identity in identities:
        status, _ = request('https://identitytoolkit.googleapis.com/v1/accounts:delete?key=' + key,
                            {'idToken': identity['idToken']})
        print('TEST_IDENTITY_CLEANUP=' + ('PASS' if status == 200 else 'FAILED'), flush=True)
